/**
 * GENERATED by scripts/export-deployments.ts from packages/memefun-contracts/deployments.
 * Do not edit by hand: deploy, then run `pnpm deployments`.
 */
import type { Address } from "@/core/types";

export interface MemefunDeployment {
  chainId: number;
  deployedAtBlock: number;
  poolManager: Address;
  config: Address;
  feeVault: Address;
  factory: Address;
  router: Address;
  hook: Address;
  buybackBurnVault: Address;
  floorVault: Address;
  holderRewardDistributor: Address;
  usdc: Address;
  /** Testnets only: the test stock and the faucet that mints it. */
  stock?: Address;
  stockFaucet?: Address;
}

export const DEPLOYMENTS: Readonly<Record<number, MemefunDeployment>> = {};
