/**
 * GENERATED by scripts/export-deployments.ts from packages/memefun-contracts/deployments.
 * Do not edit by hand: deploy, then run `pnpm deployments`.
 */
import type { Address } from "@/core/types";

export interface MemefunDeployment {
  chainId: number;
  deployedAtBlock: number;
  poolManager: Address;
  config: Address;
  feeVault: Address;
  factory: Address;
  router: Address;
  hook: Address;
  buybackBurnVault: Address;
  floorVault: Address;
  holderRewardDistributor: Address;
  usdc: Address;
  /** Testnets only: the test stock and the faucet that mints it. */
  stock?: Address;
  stockFaucet?: Address;
}

export const DEPLOYMENTS: Readonly<Record<number, MemefunDeployment>> = {
  8453: {
    chainId: 8453,
    deployedAtBlock: 52231158,
    poolManager: "0x498581fF718922c3f8e6A244956aF099B2652b2b",
    config: "0x1a9BfE7281C4d357d1a58b0833C2438bAc340b12",
    feeVault: "0xfe62622b5757dF8d8f6547bB227b5D339a92042D",
    factory: "0xEb462A3B379266e2860959b821A98bBD2F289BB2",
    router: "0x9378BE418785C1fF49EE302197Be876371FC5f39",
    hook: "0x87a4E12530071269F0671a2f064aFFfbFE74EAeC",
    buybackBurnVault: "0x7a24F98e23b1c147c1cB2c70ca5937A282f8754a",
    floorVault: "0x452dC6a3dD5D5D7339b6A1bBdD61dB9d652e0268",
    holderRewardDistributor: "0x5d3fb4713160c9f51A5ce4d6c997f8eF23A0d24A",
    usdc: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913",
  },
  84532: {
    chainId: 84532,
    deployedAtBlock: 47708210,
    poolManager: "0x05E73354cFDd6745C338b50BcFDfA3Aa6fA03408",
    config: "0x54C177426033d50686bA7D36B690d1a2d7E34625",
    feeVault: "0xBe6A2F9C0c5433486b2eE82F69EE01D407962f40",
    factory: "0xE937168b4189Db1063426F9A46bd42E1E574b8c8",
    router: "0x1C63760c2E021b9d3b7d0dD30D94b0aA95CB7B3c",
    hook: "0x54a2a323d98fd8C60B3A888B73aF580DFd066aec",
    buybackBurnVault: "0x329645EfdFf100380567Db367566af5b67917E41",
    floorVault: "0xB04051910d87585e3297bf33e7890dfFc670d3e5",
    holderRewardDistributor: "0x248D2290beC9b2Ffd66a763c4B447b7adE79AE0b",
    usdc: "0x036CbD53842c5426634e7929541eC2318f3dCF7e",
  },
};
