/**
 * Preview coin catalog. Every name is original: no real coins, brands or
 * people, so the preview can never be mistaken for a listing of live assets.
 */
export const PREVIEW_COINS: Array<{ name: string; symbol: string; description: string; stock?: boolean }> = [
  { name: "Dust Bunny", symbol: "DBUN", description: "Born from the crumbs of a thousand swaps. Sweeps nothing, hoards everything." },
  { name: "Based Toad", symbol: "TOAD", description: "Sits on a lily pad on Base and waits for the next block." },
  { name: "Blue Hour", symbol: "BLUE", description: "For the people who trade when the sky turns Base blue." },
  { name: "Gas Goblin", symbol: "GOBL", description: "Lives under the mempool. Eats basis points for breakfast." },
  { name: "Pixel Pup", symbol: "PUP", description: "An 8-bit dog with a 64-bit appetite." },
  { name: "Night Shift Cat", symbol: "NSCAT", description: "Watches charts at 3am so you do not have to." },
  { name: "Onchain Owl", symbol: "OWL", description: "Wise enough to read the contract before buying." },
  { name: "Mint Condition", symbol: "MINT", description: "Fresh out of the factory. Never touched by an admin key." },
  { name: "Lunch Money", symbol: "LUNCH", description: "The coin you buy with what is left after the sandwich." },
  { name: "Gm Cactus", symbol: "CACTUS", description: "Says gm every day, even in a bear market desert." },
  { name: "Slow Snail", symbol: "SNAIL", description: "Not in a hurry. Liquidity is locked forever anyway." },
  { name: "Tiny Whale", symbol: "TWHALE", description: "Small fish energy, whale-sized dreams." },
  { name: "Paper Plane", symbol: "PLANE", description: "Folded from a whitepaper nobody read." },
  { name: "Big Brain Bee", symbol: "BEE", description: "Did the math on the bonding curve. Still bought." },
  { name: "Sock Puppet", symbol: "SOCK", description: "Every holder is definitely a different person." },
  { name: "Laser Llama", symbol: "LLAMA", description: "Eyes on the next milestone ring." },
  { name: "Couch Potato", symbol: "SPUD", description: "Holds from the sofa. Claims rewards from the sofa." },
  { name: "Bubble Tea", symbol: "BOBA", description: "Sweet, chewy, slightly volatile." },
  { name: "Rubber Duck", symbol: "QUACK", description: "Debugs your portfolio by listening quietly." },
  { name: "Space Hamster", symbol: "HAMS", description: "Running the wheel all the way to orbit." },
  { name: "Lucky Clover", symbol: "CLOVER", description: "Four leaves, four fee modes, one lucky holder." },
  { name: "Grumpy Cloud", symbol: "CLOUD", description: "Rains on every red candle." },
  { name: "Midnight Snack", symbol: "SNACK", description: "Bought at 2am, regretted at 9am, held at noon." },
  { name: "Disco Shrimp", symbol: "SHRIMP", description: "Small, pink, dances on every pump." },
  { name: "Chill Penguin", symbol: "CHILL", description: "Ice cold hands. Diamond flippers." },
  { name: "Crypto Kettle", symbol: "KETTLE", description: "Whistles when the chart is about to boil." },
  { name: "Sleepy Sloth", symbol: "SLOTH", description: "Wakes up only for holder reward epochs." },
  { name: "Hype Hippo", symbol: "HIPPO", description: "Big mouth, bigger buys." },
  { name: "Wobbly Jelly", symbol: "JELLY", description: "Shakes on every candle and never breaks." },
  { name: "Byte Beaver", symbol: "BYTE", description: "Builds dams of permanent liquidity." },
  { name: "Frosty Fox", symbol: "FROST", description: "Cool under pressure, sly on the dips." },
  { name: "Glitch Goose", symbol: "GOOSE", description: "Honks at bad trades. Honks at good ones too." },
  { name: "Pocket Dragon", symbol: "PDRAG", description: "Breathes fire on the supply with every buyback." },
  { name: "Velvet Moose", symbol: "MOOSE", description: "Soft fur, hard floor." },
  { name: "Turbo Turtle", symbol: "TURBO", description: "Slow and steady was never the plan." },
  { name: "Coffee Bean", symbol: "BEAN", description: "Fuel for every all-night launch." },
  { name: "Pancake Panda", symbol: "PANDA", description: "Stacks pancakes and positions." },
  { name: "Salty Pretzel", symbol: "SALT", description: "For holders who sold the bottom and bought back higher." },
  { name: "Cosmic Crab", symbol: "CRAB", description: "Moves sideways until it does not." },
  { name: "Golden Goat", symbol: "GOAT", description: "Climbs every chart, eats every dip." },
  { name: "Volt Rider", symbol: "VOLT", description: "Charged up and riding a stock pair.", stock: true },
  { name: "Chip Chaser", symbol: "CHIP", description: "Chases silicon. Paired with a tokenized stock.", stock: true },
  { name: "Orchard Club", symbol: "ORCH", description: "Picks apples, holds a stock pair.", stock: true },
  { name: "Window Seat", symbol: "WSEAT", description: "Best view of the chart, paired with a stock.", stock: true },
  { name: "Neon Newt", symbol: "NEWT", description: "Glows green in the dark." },
  { name: "Lazy Lion", symbol: "LION", description: "King of the hill, mostly asleep on it." },
  { name: "Ghost Pepper", symbol: "GHOST", description: "Spicy chart, invisible sellers." },
  { name: "Waffle Wolf", symbol: "WAFFLE", description: "Howls at the moon, eats breakfast at noon." },
  { name: "Echo Parrot", symbol: "ECHO", description: "Repeats whatever the timeline says." },
  { name: "Lofi Frog", symbol: "LOFI", description: "Beats to hold coins to." },
  { name: "Mellow Mango", symbol: "MANGO", description: "Ripe for a slow and juicy climb." },
  { name: "Blocky Bear", symbol: "BLOCK", description: "Built one block at a time." },
  { name: "Stack Squirrel", symbol: "STACK", description: "Buries a little every day for winter." },
  { name: "Bloop Fish", symbol: "BLOOP", description: "Makes one sound. It means buy." },
  { name: "Zen Koala", symbol: "ZEN", description: "Unbothered by red candles." },
  { name: "Retro Robot", symbol: "RETRO", description: "Runs on vintage alpha." },
  { name: "Spicy Taco", symbol: "TACO", description: "Every Tuesday is a pump." },
  { name: "Cloud Nine", symbol: "NINE", description: "Where holders go after a milestone." },
  { name: "Snowball", symbol: "SNOW", description: "Small start, rolls downhill fast." },
  { name: "Berry Bear", symbol: "BERRY", description: "Sweet tooth for buybacks." },
  { name: "Fizzy Pop", symbol: "FIZZ", description: "Bubbles up after every burn." },
  { name: "Tick Tock Croc", symbol: "CROC", description: "Always on time for the next epoch." },
];

/** Creator handles used for preview profiles. */
export const PREVIEW_CREATOR_NAMES = [
  "fernando.base.eth",
  "gmwizard.base.eth",
  "lunchbox.base.eth",
  "tinyfund.base.eth",
  "sofa.base.eth",
  "nightowl.base.eth",
  "mintmaker.base.eth",
  "pondlife.base.eth",
  "bluehour.base.eth",
  "chartcat.base.eth",
  "dustdev.base.eth",
  "kettle.base.eth",
  "zenmaster.base.eth",
  "taco.base.eth",
  "snowfall.base.eth",
  "pixelart.base.eth",
  "brainy.base.eth",
  "crabwalk.base.eth",
];

export const PREVIEW_COMMENTS = [
  "Dev bought back in. Good sign.",
  "Burn just passed 1% of supply.",
  "Floor keeps going up every hour.",
  "Claimed my holder rewards, holding the rest.",
  "Chart looks like a staircase, I like it.",
  "Who else got in before the 25K ring closed?",
  "Liquidity locked forever, no admin key. Easy hold.",
  "Fee is only 1%, way better than the usual tax tokens.",
  "69K ring is almost closed.",
  "Sold half at 3x, keeping the rest for the ride.",
  "The mascot alone is worth it.",
  "Creator replies to everyone, rare these days.",
  "Paid 30% fee trying to snipe at launch. Lesson learned.",
  "Holder count up 40 in the last hour.",
  "Quiet accumulation phase.",
  "Buyback hit right on the dip.",
];
