import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { ETH, USDC } from "@/lib/market/quotes";
import type { LaunchInput } from "@/lib/market/Market";
import { PreviewMarket } from "./engine";

const USER = "0x00000000000000000000000000000000000000aa" as const;
const AUTHOR = "0x00000000000000000000000000000000000000bb" as const;
const PAYOUT = "0x00000000000000000000000000000000000000cc" as const;
const TREASURY = "0x00000000000000000000000000000000000000dd" as const;
const NOW = Date.UTC(2026, 9, 4, 12);
const source = { postId: "123", url: "https://x.com/alice/status/123", text: "An idea worth sharing", author: { id: "42", handle: "alice", name: "Alice" } };
const input: LaunchInput = { name: "An idea", symbol: "IDEA", image: "", description: "", links: {}, quote: ETH, mode: "creator", feeBps: 100, creatorKeepBps: 0, firstBuyQuote: 0,
  markets: [{ quote: ETH, firstBuyQuote: 0 }, { quote: USDC, firstBuyQuote: 25 }], tweet: { source, authorShareBps: 5000 } };
beforeEach(() => { vi.useFakeTimers(); vi.setSystemTime(NOW); });
afterEach(() => { vi.useRealTimers(); vi.unstubAllGlobals(); });
async function finish<T>(promise: Promise<T>) { const [value] = await Promise.all([promise, vi.runAllTimersAsync()]); return value; }

describe("preview post-author ownership", () => {
  it("reserves the author portion before verification and isolates X identity when wallets switch", async () => {
    const market = new PreviewMarket({ now: NOW, empty: true });
    const coin = await finish(market.launch(USER, input));
    expect(coin.markets![1]!.stats.creatorEarnedQuote).toBeCloseTo(0.1, 12);
    expect(market.getAuthorRewards(AUTHOR)).toEqual([]);
    await market.beginAuthorVerification(AUTHOR, coin.address);
    expect(market.getAuthorRewards(AUTHOR)[0]!.amountQuote).toBeCloseTo(0.1, 12);
    expect(market.getAuthorSession(PAYOUT)).toBeNull();
    expect(market.getAuthorRewards(PAYOUT)).toEqual([]);
    await expect(market.bindAuthorWallet(PAYOUT, coin.address)).rejects.toThrow("X account first");
  });
  it("binds one permanent earning wallet, keeps author rights separate from creator transfers, and never redirects an author payout", async () => {
    const market = new PreviewMarket({ now: NOW, empty: true });
    const coin = await finish(market.launch(USER, input));
    market.ensureUser(AUTHOR); market.ensureUser(PAYOUT);
    await market.beginAuthorVerification(AUTHOR, coin.address);
    await market.bindAuthorWallet(AUTHOR, coin.address);
    await market.proposeCreator(USER, coin.address, PAYOUT);
    await market.acceptCreator(PAYOUT, coin.address);
    expect(market.getCoin(coin.address)!.tweet!.authorWallet).toBe(AUTHOR);
    const before = market.getQuoteBalance(AUTHOR, "USDC");
    const payoutBefore = market.getQuoteBalance(PAYOUT, "USDC");
    const claims = market.getClaimables(AUTHOR).filter((item) => item.kind === "author");
    await finish(market.claim(AUTHOR, claims, "ok", undefined, PAYOUT));
    expect(market.getQuoteBalance(AUTHOR, "USDC")).toBeCloseTo(before + 0.1, 10);
    expect(market.getQuoteBalance(PAYOUT, "USDC")).toBe(payoutBefore);
    expect(market.getAuthorRewards(AUTHOR)).toEqual([]);
    vi.setSystemTime(coin.tweet!.treasuryUnlockAt + 1);
    await finish(market.trade(PAYOUT, coin.address, "buy", 10, 0, { poolId: coin.markets![1]!.poolId }));
    expect(market.getAuthorRewards(AUTHOR)[0]!.amountQuote).toBeGreaterThan(0);
    await market.claimAuthorRewards(AUTHOR, coin.address);
  });
  it("allows late verification and claims while new author fees keep accruing after the treasury unlock", async () => {
    const market = new PreviewMarket({ now: NOW, empty: true });
    const coin = await finish(market.launch(USER, input));
    market.ensureUser(AUTHOR);
    await market.beginAuthorVerification(AUTHOR, coin.address);
    vi.setSystemTime(coin.tweet!.treasuryUnlockAt);
    expect(market.getCoin(coin.address)!.tweet!.treasuryUnlocked).toBe(true);
    const reserved = market.getAuthorRewards(AUTHOR)[0]!.amountQuote;
    const oldPlatform = market.getCoin(coin.address)!.markets![1]!.stats.platformQuote;
    const trade = await finish(market.trade(USER, coin.address, "buy", 10, 0, { poolId: coin.markets![1]!.poolId }));
    expect(market.getAuthorRewards(AUTHOR)[0]!.amountQuote).toBeCloseTo(reserved + trade.feeQuote * 0.4, 12);
    expect(market.getCoin(coin.address)!.markets![1]!.stats.platformQuote - oldPlatform).toBeCloseTo(trade.feeQuote * 0.2, 12);
    expect(market.getCoin(coin.address)!.tweet!.reclaimed).not.toBe(true);
    await market.bindAuthorWallet(AUTHOR, coin.address);
    const pending = market.getAuthorRewards(AUTHOR)[0]!.amountQuote;
    const balance = market.getQuoteBalance(AUTHOR, "USDC");
    await market.claimAuthorRewards(AUTHOR, coin.address);
    expect(market.getQuoteBalance(AUTHOR, "USDC")).toBeCloseTo(balance + pending, 10);
    expect(market.getAuthorRewards(AUTHOR)).toEqual([]);
  });
  it("allows only the configured treasury after 180 days, scopes the withdrawal to one currency, and preserves future earnings", async () => {
    const market = new PreviewMarket({ now: NOW, empty: true, treasury: TREASURY });
    const coin = await finish(market.launch(USER, input));
    market.ensureUser(AUTHOR); market.ensureUser(TREASURY);
    expect(market.isAuthorTreasury(TREASURY)).toBe(true);
    expect(market.isAuthorTreasury(USER)).toBe(false);
    expect(market.isAuthorTreasury()).toBe(false);
    await expect(market.getTreasuryAuthorRewards(USER, coin.address)).rejects.toThrow("Only the treasury");
    await market.beginAuthorVerification(AUTHOR, coin.address);
    await finish(market.trade(USER, coin.address, "buy", 0.05, 0, { poolId: coin.markets![0]!.poolId }));
    const pending = market.getAuthorRewards(AUTHOR);
    const usdc = pending.find((reward) => reward.quoteSymbol === "USDC")!;
    const eth = pending.find((reward) => reward.quoteSymbol === "ETH")!;
    const treasuryUsdc = market.getQuoteBalance(TREASURY, "USDC");
    const treasuryEth = market.getQuoteBalance(TREASURY, "ETH");
    const authorUsdc = market.getQuoteBalance(AUTHOR, "USDC");
    const treasuryRows = await market.getTreasuryAuthorRewards(TREASURY, coin.address);
    expect(treasuryRows.find((reward) => reward.quoteSymbol === "USDC")).toMatchObject({ poolId: usdc.poolId, currency: USDC.address, amountRaw: "100000" });
    vi.setSystemTime(coin.tweet!.treasuryUnlockAt - 1);
    await expect(market.claimTreasuryAuthorRewards(TREASURY, coin.address, usdc.poolId)).rejects.toThrow("unlock");
    vi.setSystemTime(coin.tweet!.treasuryUnlockAt);
    await expect(market.claimTreasuryAuthorRewards(USER, coin.address, usdc.poolId)).rejects.toThrow("Only the treasury");
    expect(market.getAuthorRewards(AUTHOR)).toEqual(pending);
    await market.claimTreasuryAuthorRewards(TREASURY, coin.address, usdc.poolId);
    expect(market.getQuoteBalance(TREASURY, "USDC")).toBeCloseTo(treasuryUsdc + usdc.amountQuote, 10);
    expect(market.getQuoteBalance(TREASURY, "ETH")).toBe(treasuryEth);
    expect(market.getQuoteBalance(AUTHOR, "USDC")).toBe(authorUsdc);
    expect(market.getAuthorRewards(AUTHOR)).toEqual([eth]);
    expect((await market.getTreasuryAuthorRewards(TREASURY, coin.address)).find((reward) => reward.quoteSymbol === "USDC")!.amountRaw).toBe("0");
    expect(market.getCoin(coin.address)!.tweet!.reclaimed).toBe(true);
    await market.bindAuthorWallet(AUTHOR, coin.address);
    await market.claimAuthorRewards(AUTHOR, coin.address);
    expect(market.getAuthorRewards(AUTHOR)).toEqual([]);
    expect((await market.getTreasuryAuthorRewards(TREASURY, coin.address)).every((reward) => reward.amountQuote === 0)).toBe(true);
    await finish(market.trade(USER, coin.address, "buy", 10, 0, { poolId: usdc.poolId }));
    expect(market.getAuthorRewards(AUTHOR)[0]!.amountQuote).toBeGreaterThan(0);
    expect(market.getClaimables(AUTHOR).filter((item) => item.kind === "author")).toHaveLength(1);
    await market.claimAuthorRewards(AUTHOR, coin.address);
    expect(market.getAuthorRewards(AUTHOR)).toEqual([]);
  });
  it("lets treasury withdraw a verified author's new balance after earlier claims without paying stale claims twice", async () => {
    const market = new PreviewMarket({ now: NOW, empty: true, treasury: TREASURY });
    const coin = await finish(market.launch(USER, input));
    market.ensureUser(TREASURY);
    const poolId = coin.markets![1]!.poolId;
    await market.beginAuthorVerification(AUTHOR, coin.address);
    await market.bindAuthorWallet(AUTHOR, coin.address);
    await market.claimAuthorRewards(AUTHOR, coin.address);
    const authorBalance = market.getQuoteBalance(AUTHOR, "USDC");
    await finish(market.trade(USER, coin.address, "buy", 10, 0, { poolId }));
    const stale = market.getClaimables(AUTHOR).filter((item) => item.kind === "author");
    const pending = stale[0]!.amountQuote;
    const treasuryBalance = market.getQuoteBalance(TREASURY, "USDC");
    vi.setSystemTime(coin.tweet!.treasuryUnlockAt);
    await market.reclaimAuthorRewards(TREASURY, coin.address, poolId);
    expect(market.getQuoteBalance(TREASURY, "USDC")).toBeCloseTo(treasuryBalance + pending, 10);
    await expect(finish(market.claim(AUTHOR, stale))).rejects.toThrow("no unpaid author rewards");
    expect(market.getQuoteBalance(AUTHOR, "USDC")).toBe(authorBalance);
    expect(market.getAuthorRewards(AUTHOR)).toEqual([]);
    await finish(market.trade(USER, coin.address, "buy", 10, 0, { poolId }));
    const newPending = market.getAuthorRewards(AUTHOR)[0]!.amountQuote;
    await market.claimAuthorRewards(AUTHOR, coin.address);
    expect(market.getQuoteBalance(AUTHOR, "USDC")).toBeCloseTo(authorBalance + newPending, 10);
    await expect(market.reclaimAuthorRewards(TREASURY, coin.address, poolId)).rejects.toThrow("no unpaid author rewards");
    await finish(market.trade(USER, coin.address, "buy", 10, 0, { poolId }));
    const finalPending = market.getAuthorRewards(AUTHOR)[0]!.amountQuote;
    await market.reclaimAuthorRewards(TREASURY, coin.address, poolId);
    expect(market.getQuoteBalance(TREASURY, "USDC")).toBeCloseTo(treasuryBalance + pending + finalPending, 10);
    expect(market.getAuthorRewards(AUTHOR)).toEqual([]);
  });
  it("never fabricates a source when server import is unavailable", async () => {
    const market = new PreviewMarket({ now: NOW, empty: true });
    const request = vi.fn().mockResolvedValue({ ok: false, json: async () => ({ error: { message: "Import unavailable" } }) });
    vi.stubGlobal("fetch", request);
    await expect(market.importTweet(source.url)).rejects.toThrow("Import unavailable");
    expect(request.mock.calls[0]![0]).toBe("/api/tweets/import");
    expect(JSON.parse(request.mock.calls[0]![1].body).url).toBe("https://x.com/i/status/123");
  });
});
