/**
 * Copies the memefun contract ABIs from the Foundry build into the app, typed `as const` so
 * viem and wagmi infer every argument and return type.
 *
 *   cd packages/memefun-contracts && forge build
 *   cd apps/memefun && pnpm abis
 *
 * Writes src/lib/contracts/abis.ts. Deterministic: same build, same file.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const outDir = resolve(here, "../../../packages/memefun-contracts/out");
const target = resolve(here, "../src/lib/contracts/abis.ts");

const CONTRACTS: Array<[file: string, name: string, exportName: string]> = [
  ["MemeFunConfig.sol", "MemeFunConfig", "memeFunConfigAbi"],
  ["MemeFunFactory.sol", "MemeFunFactory", "memeFunFactoryAbi"],
  ["MemeFunHook.sol", "MemeFunHook", "memeFunHookAbi"],
  ["MemeFunRouter.sol", "MemeFunRouter", "memeFunRouterAbi"],
  ["FeeVault.sol", "FeeVault", "feeVaultAbi"],
  ["BuybackBurnVault.sol", "BuybackBurnVault", "buybackBurnVaultAbi"],
  ["FloorVault.sol", "FloorVault", "floorVaultAbi"],
  ["HolderRewardDistributor.sol", "HolderRewardDistributor", "holderRewardDistributorAbi"],
];

let body = `/**\n * GENERATED by scripts/export-abis.ts from packages/memefun-contracts/out. Do not edit by hand.\n */\n`;
for (const [file, name, exportName] of CONTRACTS) {
  const artifact = JSON.parse(readFileSync(resolve(outDir, file, `${name}.json`), "utf8")) as { abi: unknown[] };
  body += `\nexport const ${exportName} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;
  console.log(`${name}: ${artifact.abi.length} entries`);
}
mkdirSync(dirname(target), { recursive: true });
writeFileSync(target, body);
console.log(`wrote ${target}`);
