/**
 * Copies the contract addresses of every public deployment into the app, so the addresses users
 * approve and send funds to are part of the reviewed build, never something a server hands out.
 *
 *   cd apps/memefun && pnpm deployments
 *
 * Reads packages/memefun-contracts/deployments/<chainId>.json (written by Deploy.s.sol and
 * TestnetExtras.s.sol) and writes src/lib/contracts/deployments.ts. The local chain (31337) is
 * skipped: a dev build reads it from its own local API instead.
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { getAddress } from "viem";

const here = dirname(fileURLToPath(import.meta.url));
const sourceDir = resolve(here, "../../../packages/memefun-contracts/deployments");
const target = resolve(here, "../src/lib/contracts/deployments.ts");

const REQUIRED = [
  "poolManager",
  "config",
  "feeVault",
  "factory",
  "router",
  "hook",
  "buybackBurnVault",
  "floorVault",
  "holderRewardDistributor",
  "usdc",
] as const;
const OPTIONAL = ["stock", "stockFaucet"] as const;

const entries: string[] = [];
const files = existsSync(sourceDir) ? readdirSync(sourceDir).filter((name) => /^\d+\.json$/.test(name)) : [];
for (const name of files.sort((a, b) => Number.parseInt(a, 10) - Number.parseInt(b, 10))) {
  const json = JSON.parse(readFileSync(resolve(sourceDir, name), "utf8")) as Record<string, unknown>;
  const chainId = Number(json.chainId);
  if (chainId === 31337) continue;
  if (`${chainId}.json` !== name) throw new Error(`${name} says chainId ${chainId}`);
  const fields: string[] = [`chainId: ${chainId}`, `deployedAtBlock: ${Number(json.deployedAtBlock)}`];
  for (const key of REQUIRED) {
    if (typeof json[key] !== "string") throw new Error(`${name} has no ${key}`);
    fields.push(`${key}: "${getAddress(json[key] as string)}"`);
  }
  for (const key of OPTIONAL) {
    if (typeof json[key] === "string") fields.push(`${key}: "${getAddress(json[key] as string)}"`);
  }
  entries.push(`  ${chainId}: {\n    ${fields.join(",\n    ")},\n  },`);
  console.log(`chain ${chainId}: ${REQUIRED.length} contracts${json.stock ? " + test stock and faucet" : ""}`);
}

const body = `/**
 * GENERATED by scripts/export-deployments.ts from packages/memefun-contracts/deployments.
 * Do not edit by hand: deploy, then run \`pnpm deployments\`.
 */
import type { Address } from "@/core/types";

export interface MemefunDeployment {
  chainId: number;
  deployedAtBlock: number;
  poolManager: Address;
  config: Address;
  feeVault: Address;
  factory: Address;
  router: Address;
  hook: Address;
  buybackBurnVault: Address;
  floorVault: Address;
  holderRewardDistributor: Address;
  usdc: Address;
  /** Testnets only: the test stock and the faucet that mints it. */
  stock?: Address;
  stockFaucet?: Address;
}

export const DEPLOYMENTS: Readonly<Record<number, MemefunDeployment>> = {${entries.length > 0 ? `\n${entries.join("\n")}\n` : ""}};
`;
writeFileSync(target, body);
console.log(`wrote ${target} (${entries.length} chain${entries.length === 1 ? "" : "s"})`);
