import { createPublicClient, http, type PublicClient } from "viem";
import {
  apeChain,
  arbitrum,
  aurora,
  avalanche,
  base,
  berachain,
  blast,
  bsc,
  celo,
  cronos,
  fantom,
  flare,
  gnosis,
  gravity,
  harmonyOne,
  hyperEvm,
  injective,
  kava,
  linea,
  mainnet,
  manta,
  mantle,
  metis,
  mode,
  monad,
  moonriver,
  opBNB,
  optimism,
  plasma,
  plumeMainnet,
  polygon,
  polygonZkEvm,
  rootstock,
  scroll,
  sei,
  sonic,
  swellchain,
  tac,
  telos,
  unichain,
  zksync,
  type Chain,
} from "viem/chains";

type SwapChainConfig = {
  id: number;
  key: string;
  label: string;
  chain: Chain;
  rpcEnv: string;
  openOceanSlug?: string;
  coinGeckoPlatformId?: string;
  nativeCoinGeckoId: string;
  wrappedNativeTokens?: readonly string[];
};

export const SUPPORTED_SWAP_CHAINS = [
  {
    id: base.id,
    key: "base",
    label: "Base",
    chain: base,
    rpcEnv: "BASE_RPC_URL",
    openOceanSlug: "base",
    coinGeckoPlatformId: "base",
    nativeCoinGeckoId: "ethereum",
    wrappedNativeTokens: ["0x4200000000000000000000000000000000000006"],
  },
  {
    id: mainnet.id,
    key: "ethereum",
    label: "Ethereum",
    chain: mainnet,
    rpcEnv: "ETHEREUM_RPC_URL",
    openOceanSlug: "eth",
    coinGeckoPlatformId: "ethereum",
    nativeCoinGeckoId: "ethereum",
    wrappedNativeTokens: ["0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"],
  },
  {
    id: arbitrum.id,
    key: "arbitrum",
    label: "Arbitrum",
    chain: arbitrum,
    rpcEnv: "ARBITRUM_RPC_URL",
    openOceanSlug: "arbitrum",
    coinGeckoPlatformId: "arbitrum-one",
    nativeCoinGeckoId: "ethereum",
    wrappedNativeTokens: ["0x82af49447d8a07e3bd95bd0d56f35241523fbab1"],
  },
  {
    id: optimism.id,
    key: "optimism",
    label: "Optimism",
    chain: optimism,
    rpcEnv: "OPTIMISM_RPC_URL",
    openOceanSlug: "optimism",
    coinGeckoPlatformId: "optimistic-ethereum",
    nativeCoinGeckoId: "ethereum",
    wrappedNativeTokens: ["0x4200000000000000000000000000000000000006"],
  },
  {
    id: polygon.id,
    key: "polygon",
    label: "Polygon",
    chain: polygon,
    rpcEnv: "POLYGON_RPC_URL",
    openOceanSlug: "polygon",
    coinGeckoPlatformId: "polygon-pos",
    nativeCoinGeckoId: "matic-network",
    wrappedNativeTokens: ["0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270"],
  },
  {
    id: bsc.id,
    key: "bsc",
    label: "BNB Chain",
    chain: bsc,
    rpcEnv: "BSC_RPC_URL",
    openOceanSlug: "bsc",
    coinGeckoPlatformId: "binance-smart-chain",
    nativeCoinGeckoId: "binancecoin",
    wrappedNativeTokens: ["0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c"],
  },
  {
    id: avalanche.id,
    key: "avalanche",
    label: "Avalanche",
    chain: avalanche,
    rpcEnv: "AVALANCHE_RPC_URL",
    openOceanSlug: "avax",
    coinGeckoPlatformId: "avalanche",
    nativeCoinGeckoId: "avalanche-2",
    wrappedNativeTokens: ["0xb31f66aa3c1e785363f0875a1b74e27b85fd66c7"],
  },
  {
    id: zksync.id,
    key: "zksync",
    label: "zkSync Era",
    chain: zksync,
    rpcEnv: "ZKSYNC_RPC_URL",
    openOceanSlug: "zksync",
    coinGeckoPlatformId: "zksync",
    nativeCoinGeckoId: "ethereum",
  },
  {
    id: fantom.id,
    key: "fantom",
    label: "Fantom",
    chain: fantom,
    rpcEnv: "FANTOM_RPC_URL",
    openOceanSlug: "fantom",
    coinGeckoPlatformId: "fantom",
    nativeCoinGeckoId: "fantom",
    wrappedNativeTokens: ["0x21be370d5312f44cb42ce377bc9b8a0cef1a4c83"],
  },
  {
    id: sonic.id,
    key: "sonic",
    label: "Sonic",
    chain: sonic,
    rpcEnv: "SONIC_RPC_URL",
    openOceanSlug: "sonic",
    coinGeckoPlatformId: "sonic",
    nativeCoinGeckoId: "sonic-3",
  },
  {
    id: berachain.id,
    key: "berachain",
    label: "Berachain",
    chain: berachain,
    rpcEnv: "BERACHAIN_RPC_URL",
    openOceanSlug: "bera",
    coinGeckoPlatformId: "berachain",
    nativeCoinGeckoId: "berachain-bera",
  },
  {
    id: linea.id,
    key: "linea",
    label: "Linea",
    chain: linea,
    rpcEnv: "LINEA_RPC_URL",
    openOceanSlug: "linea",
    coinGeckoPlatformId: "linea",
    nativeCoinGeckoId: "ethereum",
  },
  {
    id: hyperEvm.id,
    key: "hyperevm",
    label: "HyperEVM",
    chain: hyperEvm,
    rpcEnv: "HYPEREVM_RPC_URL",
    openOceanSlug: "hyperevm",
    coinGeckoPlatformId: "hyperevm",
    nativeCoinGeckoId: "hyperliquid",
  },
  {
    id: plasma.id,
    key: "plasma",
    label: "Plasma",
    chain: plasma,
    rpcEnv: "PLASMA_RPC_URL",
    openOceanSlug: "plasma",
    coinGeckoPlatformId: "plasma",
    nativeCoinGeckoId: "plasma",
  },
  {
    id: monad.id,
    key: "monad",
    label: "Monad",
    chain: monad,
    rpcEnv: "MONAD_RPC_URL",
    openOceanSlug: "monad",
    coinGeckoPlatformId: "monad",
    nativeCoinGeckoId: "monad",
  },
  {
    id: injective.id,
    key: "injective",
    label: "Injective",
    chain: injective,
    rpcEnv: "INJECTIVE_RPC_URL",
    openOceanSlug: "injective",
    coinGeckoPlatformId: "injective",
    nativeCoinGeckoId: "injective-protocol",
  },
  {
    id: scroll.id,
    key: "scroll",
    label: "Scroll",
    chain: scroll,
    rpcEnv: "SCROLL_RPC_URL",
    openOceanSlug: "scroll",
    coinGeckoPlatformId: "scroll",
    nativeCoinGeckoId: "ethereum",
  },
  {
    id: blast.id,
    key: "blast",
    label: "Blast",
    chain: blast,
    rpcEnv: "BLAST_RPC_URL",
    openOceanSlug: "blast",
    coinGeckoPlatformId: "blast",
    nativeCoinGeckoId: "ethereum",
  },
  {
    id: mode.id,
    key: "mode",
    label: "Mode",
    chain: mode,
    rpcEnv: "MODE_RPC_URL",
    openOceanSlug: "mode",
    coinGeckoPlatformId: "mode",
    nativeCoinGeckoId: "ethereum",
  },
  {
    id: mantle.id,
    key: "mantle",
    label: "Mantle",
    chain: mantle,
    rpcEnv: "MANTLE_RPC_URL",
    openOceanSlug: "mantle",
    coinGeckoPlatformId: "mantle",
    nativeCoinGeckoId: "mantle",
  },
  {
    id: unichain.id,
    key: "unichain",
    label: "Unichain",
    chain: unichain,
    rpcEnv: "UNICHAIN_RPC_URL",
    openOceanSlug: "uni",
    coinGeckoPlatformId: "unichain",
    nativeCoinGeckoId: "ethereum",
  },
  {
    id: gnosis.id,
    key: "gnosis",
    label: "Gnosis",
    chain: gnosis,
    rpcEnv: "GNOSIS_RPC_URL",
    openOceanSlug: "xdai",
    coinGeckoPlatformId: "xdai",
    nativeCoinGeckoId: "xdai",
  },
  {
    id: celo.id,
    key: "celo",
    label: "Celo",
    chain: celo,
    rpcEnv: "CELO_RPC_URL",
    openOceanSlug: "celo",
    coinGeckoPlatformId: "celo",
    nativeCoinGeckoId: "celo",
  },
  {
    id: metis.id,
    key: "metis",
    label: "Metis",
    chain: metis,
    rpcEnv: "METIS_RPC_URL",
    openOceanSlug: "metis",
    coinGeckoPlatformId: "metis-andromeda",
    nativeCoinGeckoId: "metis-token",
  },
  {
    id: polygonZkEvm.id,
    key: "polygon-zkevm",
    label: "Polygon zkEVM",
    chain: polygonZkEvm,
    rpcEnv: "POLYGON_ZKEVM_RPC_URL",
    openOceanSlug: "polygon_zkevm",
    coinGeckoPlatformId: "polygon-zkevm",
    nativeCoinGeckoId: "ethereum",
  },
  {
    id: kava.id,
    key: "kava",
    label: "Kava",
    chain: kava,
    rpcEnv: "KAVA_RPC_URL",
    openOceanSlug: "kava",
    coinGeckoPlatformId: "kava",
    nativeCoinGeckoId: "kava",
  },
  {
    id: opBNB.id,
    key: "opbnb",
    label: "opBNB",
    chain: opBNB,
    rpcEnv: "OPBNB_RPC_URL",
    openOceanSlug: "opbnb",
    coinGeckoPlatformId: "opbnb",
    nativeCoinGeckoId: "binancecoin",
  },
  {
    id: cronos.id,
    key: "cronos",
    label: "Cronos",
    chain: cronos,
    rpcEnv: "CRONOS_RPC_URL",
    openOceanSlug: "cronos",
    coinGeckoPlatformId: "cronos",
    nativeCoinGeckoId: "crypto-com-chain",
  },
  {
    id: aurora.id,
    key: "aurora",
    label: "Aurora",
    chain: aurora,
    rpcEnv: "AURORA_RPC_URL",
    openOceanSlug: "aurora",
    coinGeckoPlatformId: "aurora",
    nativeCoinGeckoId: "ethereum",
  },
  {
    id: moonriver.id,
    key: "moonriver",
    label: "Moonriver",
    chain: moonriver,
    rpcEnv: "MOONRIVER_RPC_URL",
    openOceanSlug: "moonriver",
    coinGeckoPlatformId: "moonriver",
    nativeCoinGeckoId: "moonriver",
  },
  {
    id: harmonyOne.id,
    key: "harmony",
    label: "Harmony",
    chain: harmonyOne,
    rpcEnv: "HARMONY_RPC_URL",
    openOceanSlug: "harmony",
    coinGeckoPlatformId: "harmony-shard-0",
    nativeCoinGeckoId: "harmony",
  },
  {
    id: sei.id,
    key: "sei",
    label: "Sei",
    chain: sei,
    rpcEnv: "SEI_RPC_URL",
    openOceanSlug: "sei",
    coinGeckoPlatformId: "sei-network",
    nativeCoinGeckoId: "sei-network",
  },
  {
    id: apeChain.id,
    key: "apechain",
    label: "ApeChain",
    chain: apeChain,
    rpcEnv: "APECHAIN_RPC_URL",
    openOceanSlug: "ape",
    coinGeckoPlatformId: "apechain",
    nativeCoinGeckoId: "apecoin",
  },
  {
    id: flare.id,
    key: "flare",
    label: "Flare",
    chain: flare,
    rpcEnv: "FLARE_RPC_URL",
    openOceanSlug: "flare",
    coinGeckoPlatformId: "flare-network",
    nativeCoinGeckoId: "flare-networks",
  },
  {
    id: rootstock.id,
    key: "rootstock",
    label: "Rootstock",
    chain: rootstock,
    rpcEnv: "ROOTSTOCK_RPC_URL",
    openOceanSlug: "rootstock",
    coinGeckoPlatformId: "rootstock",
    nativeCoinGeckoId: "rootstock",
  },
  {
    id: gravity.id,
    key: "gravity",
    label: "Gravity",
    chain: gravity,
    rpcEnv: "GRAVITY_RPC_URL",
    openOceanSlug: "gravity",
    coinGeckoPlatformId: "gravity",
    nativeCoinGeckoId: "gravity",
  },
  {
    id: swellchain.id,
    key: "swell",
    label: "Swell",
    chain: swellchain,
    rpcEnv: "SWELL_RPC_URL",
    openOceanSlug: "swell",
    coinGeckoPlatformId: "swellchain",
    nativeCoinGeckoId: "ethereum",
  },
  {
    id: plumeMainnet.id,
    key: "plume",
    label: "Plume",
    chain: plumeMainnet,
    rpcEnv: "PLUME_RPC_URL",
    openOceanSlug: "plume",
    coinGeckoPlatformId: "plume",
    nativeCoinGeckoId: "plume",
  },
  {
    id: tac.id,
    key: "tac",
    label: "TAC",
    chain: tac,
    rpcEnv: "TAC_RPC_URL",
    openOceanSlug: "tac",
    coinGeckoPlatformId: "tac",
    nativeCoinGeckoId: "tac",
  },
  {
    id: telos.id,
    key: "telos",
    label: "Telos",
    chain: telos,
    rpcEnv: "TELOS_RPC_URL",
    openOceanSlug: "telos",
    coinGeckoPlatformId: "telos",
    nativeCoinGeckoId: "telos",
  },
  {
    id: manta.id,
    key: "manta",
    label: "Manta Pacific",
    chain: manta,
    rpcEnv: "MANTA_RPC_URL",
    openOceanSlug: "manta",
    coinGeckoPlatformId: "manta-pacific",
    nativeCoinGeckoId: "ethereum",
  },
] as const satisfies readonly SwapChainConfig[];

const chainConfigById = new Map<number, SwapChainConfig>(
  SUPPORTED_SWAP_CHAINS.map((chain) => [chain.id, chain])
);
const clientByChainId = new Map<number, PublicClient>();

export function getSwapChainConfig(chainId: number) {
  return chainConfigById.get(chainId) ?? null;
}

export function getSupportedSwapChainIds() {
  return SUPPORTED_SWAP_CHAINS.map((chain) => chain.id);
}

export function isSupportedSwapChainId(chainId: number) {
  return chainConfigById.has(chainId);
}

function getRpcUrl(config: SwapChainConfig) {
  return (
    process.env[config.rpcEnv] ||
    process.env[`NEXT_PUBLIC_${config.rpcEnv}`] ||
    process.env[`RPC_URL_${config.id}`] ||
    process.env[`CHAIN_${config.id}_RPC_URL`] ||
    config.chain.rpcUrls.default.http[0]
  );
}

export function getPublicClientForSwapChain(chainId: number) {
  const config = getSwapChainConfig(chainId);
  if (!config) {
    return null;
  }

  const existing = clientByChainId.get(chainId);
  if (existing) {
    return existing;
  }

  const client = createPublicClient({
    chain: config.chain,
    transport: http(getRpcUrl(config)),
  });
  clientByChainId.set(chainId, client);
  return client;
}
