// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

import {console2} from "forge-std/Script.sol";
import {Deploy} from "./Deploy.s.sol";
import {FeeVault} from "../src/FeeVault.sol";
import {MemeFunConfig} from "../src/MemeFunConfig.sol";
import {MemeFunFactory} from "../src/MemeFunFactory.sol";
import {MemeFunHook} from "../src/MemeFunHook.sol";
import {MemeFunRouter} from "../src/MemeFunRouter.sol";
import {IFeeVault} from "../src/interfaces/IFeeVault.sol";
import {IMemeFunHook} from "../src/interfaces/IMemeFunHook.sol";
import {BuybackBurnVault} from "../src/modules/BuybackBurnVault.sol";
import {FloorVault} from "../src/modules/FloorVault.sol";
import {HolderRewardDistributor} from "../src/modules/HolderRewardDistributor.sol";
import {Mode, PriceSource, QuoteKind} from "../src/types/MemeFunTypes.sol";

/// @notice Deployment alternative that attributes every actual creation/configuration write.
/// @dev Constructor ABI decoding accepts trailing bytes; the suffix changes the CREATE2 hook
///      init-code hash, so its salt MUST be mined from the attributed bytes below. It does not
///      change ordinary CREATE address derivation or contract runtime logic. A dry-run smoke
///      launch inherited from Deploy is a simulation only and is excluded from a broadcast.
contract DeployAttributed is Deploy {
    /// ERC-8021 suffix for bc_tpolfjho, generated by ox/erc8021 Attribution.toDataSuffix.
    bytes internal constant BUILDER_SUFFIX =
        hex"62635f74706f6c666a686f0b0080218021802180218021802180218021";

    struct Predicted {
        address configAt;
        address vaultAt;
        address factoryAt;
        address routerAt;
        address hookAt;
        bytes32 salt;
        bytes hookInit;
    }

    function _attributedInitCode(
        bytes memory creationCode,
        bytes memory constructorArgs
    )
        internal
        pure
        returns (bytes memory)
    {
        return bytes.concat(creationCode, constructorArgs, BUILDER_SUFFIX);
    }

    function _create(bytes memory initCode) internal returns (address deployed) {
        assembly ("memory-safe") {
            deployed := create(0, add(initCode, 0x20), mload(initCode))
        }
        require(deployed != address(0), "attributed CREATE failed");
    }

    function _sendConfig(address target, bytes memory abiCall) internal {
        (bool ok, bytes memory result) = target.call(bytes.concat(abiCall, BUILDER_SUFFIX));
        if (!ok) {
            assembly ("memory-safe") {
                revert(add(result, 0x20), mload(result))
            }
        }
    }

    function _deploy(
        address deployer,
        address treasury,
        ChainAddresses memory c
    )
        internal
        override
        returns (Deployed memory d)
    {
        uint64 nonce = vm.getNonce(deployer);
        Predicted memory p;
        p.configAt = vm.computeCreateAddress(deployer, nonce);
        p.vaultAt = vm.computeCreateAddress(deployer, nonce + 1);
        p.factoryAt = vm.computeCreateAddress(deployer, nonce + 2);
        p.routerAt = vm.computeCreateAddress(deployer, nonce + 3);
        p.hookInit = _attributedInitCode(
            type(MemeFunHook).creationCode,
            abi.encode(c.poolManager, p.factoryAt, p.vaultAt, p.routerAt)
        );
        (p.hookAt, p.salt) = _mineHookSalt(keccak256(p.hookInit));
        d.hookSalt = p.salt;
        console2.log("attributed hook address (mined):", p.hookAt);

        vm.startBroadcast(deployer);
        d.config = MemeFunConfig(
            _create(
                _attributedInitCode(
                    type(MemeFunConfig).creationCode, abi.encode(deployer, treasury)
                )
            )
        );
        d.vault = FeeVault(
            _create(
                _attributedInitCode(
                    type(FeeVault).creationCode,
                    abi.encode(c.poolManager, IMemeFunHook(p.hookAt), d.config)
                )
            )
        );
        d.factory = MemeFunFactory(
            _create(
                _attributedInitCode(
                    type(MemeFunFactory).creationCode,
                    abi.encode(c.poolManager, IMemeFunHook(p.hookAt), d.config)
                )
            )
        );
        d.router = MemeFunRouter(
            _create(
                _attributedInitCode(
                    type(MemeFunRouter).creationCode,
                    abi.encode(c.poolManager, IMemeFunHook(p.hookAt))
                )
            )
        );
        d.burnVault = BuybackBurnVault(
            _create(
                _attributedInitCode(
                    type(BuybackBurnVault).creationCode,
                    abi.encode(c.poolManager, IMemeFunHook(p.hookAt), IFeeVault(p.vaultAt))
                )
            )
        );
        d.floorVault = FloorVault(
            _create(
                _attributedInitCode(
                    type(FloorVault).creationCode,
                    abi.encode(c.poolManager, IMemeFunHook(p.hookAt), IFeeVault(p.vaultAt))
                )
            )
        );
        d.holders = HolderRewardDistributor(
            _create(
                _attributedInitCode(
                    type(HolderRewardDistributor).creationCode,
                    abi.encode(
                        c.poolManager, IMemeFunHook(p.hookAt), IFeeVault(p.vaultAt), d.config
                    )
                )
            )
        );
        (bool hookCreated,) = CREATE2_FACTORY.call(bytes.concat(p.salt, p.hookInit));
        require(hookCreated && p.hookAt.code.length != 0, "attributed CREATE2 failed");
        d.hook = MemeFunHook(p.hookAt);
        vm.stopBroadcast();

        require(address(d.config) == p.configAt, "config address moved");
        require(
            address(d.vault) == p.vaultAt, "vault address moved: deployer nonce changed mid-run"
        );
        require(address(d.factory) == p.factoryAt, "factory address moved");
        require(address(d.router) == p.routerAt, "router address moved");
        require(address(d.hook) == p.hookAt, "hook address mismatch");
    }

    function _configure(
        Deployed memory d,
        ChainAddresses memory c,
        address deployer,
        address owner,
        address keeper,
        address publisher,
        address tweetAttestor
    )
        internal
        override
    {
        vm.startBroadcast(deployer);
        address cfg = address(d.config);
        _sendConfig(
            cfg,
            abi.encodeCall(
                MemeFunConfig.listQuote,
                (address(0), QuoteKind.NATIVE, PriceSource.CHAINLINK, c.ethUsdFeed, 0, 1 days)
            )
        );
        _sendConfig(cfg, abi.encodeCall(MemeFunConfig.setQuoteEnabled, (address(0), true)));
        _sendConfig(
            cfg,
            abi.encodeCall(
                MemeFunConfig.listQuote,
                (c.usdc, QuoteKind.STABLE, PriceSource.FIXED, address(0), 1e8, 0)
            )
        );
        _sendConfig(cfg, abi.encodeCall(MemeFunConfig.setQuoteEnabled, (c.usdc, true)));
        _sendConfig(
            cfg,
            abi.encodeCall(MemeFunConfig.setModeModule, (uint256(Mode.BURN), address(d.burnVault)))
        );
        _sendConfig(
            cfg,
            abi.encodeCall(MemeFunConfig.setModeModule, (uint256(Mode.HOLDERS), address(d.holders)))
        );
        _sendConfig(
            cfg,
            abi.encodeCall(
                MemeFunConfig.setModeModule, (uint256(Mode.FLOOR), address(d.floorVault))
            )
        );
        _sendConfig(cfg, abi.encodeCall(MemeFunConfig.setModeEnabled, (uint256(Mode.BURN), true)));
        _sendConfig(
            cfg, abi.encodeCall(MemeFunConfig.setModeEnabled, (uint256(Mode.HOLDERS), true))
        );
        _sendConfig(cfg, abi.encodeCall(MemeFunConfig.setModeEnabled, (uint256(Mode.FLOOR), true)));
        if (keeper != address(0)) {
            _sendConfig(cfg, abi.encodeCall(MemeFunConfig.setPriceKeeper, (keeper)));
        }
        if (publisher != address(0)) {
            _sendConfig(cfg, abi.encodeCall(MemeFunConfig.setRewardsPublisher, (publisher)));
        }
        if (tweetAttestor != address(0)) {
            _sendConfig(cfg, abi.encodeCall(MemeFunConfig.setTweetAttestor, (tweetAttestor)));
        }
        if (owner != deployer) {
            _sendConfig(cfg, abi.encodeCall(d.config.transferOwnership, (owner)));
        }
        vm.stopBroadcast();
    }
}
